### ISSUE TITLE
Create empty documents from template.

### ISSUE THREAD

**Issue by elucian** [sage-code/carbon#2]
We have broken links on our website and this need to be fixed. Please update /carbon tutorial with new files to cover the initial chapter. You can add more chapter or change chapter names if you consider it necessary.

Copy template.html to different files and rename accordingly, then modify the bottom link so that one can navigate to next topic without going back to the index page.

Last page should point back to the index page. Change "Read Next" to "Go Back" So that user can restart from the beginning of the tutorial.

Change page title and SEO in the header. Test the page using index.html and navigate to all pages to understand how is working. If everything is fine, commit the code and push.

Note: Work in the main branch do not bother to create a dev branch.

**Comment by greenchapeljohn** [comment]
Added the base files based on the same titles used in the rust tutorials.
